from django.urls import path

from .views import (
    admin_overview,
    admin_recompute_recommendations,
    dashboard_lineup_board,
    dashboard_key_injuries,
    dashboard_opponent_summary,
    dashboard_replacement_summary,
    dashboard_top_options,
    health_check,
    injuries_collection,
    injury_update,
    match_insights,
    next_match_insights,
    player_update,
    players_collection,
    player_detail,
    player_history,
    positions_list,
    replacement_candidates,
    replacement_decision_update,
    replacement_decisions_collection,
    roster_metadata,
)

urlpatterns = [
    path("health", health_check),
    path("dashboard/top-options", dashboard_top_options),
    path("dashboard/key-injuries", dashboard_key_injuries),
    path("dashboard/replacement-summary", dashboard_replacement_summary),
    path("dashboard/opponent-summary", dashboard_opponent_summary),
    path("dashboard/lineup-board", dashboard_lineup_board),
    path("players", players_collection),
    path("players/<int:player_id>", player_detail),
    path("players/<int:player_id>/update", player_update),
    path("players/<int:player_id>/history", player_history),
    path("matches/<int:match_id>/insights", match_insights),
    path("matches/next-insights", next_match_insights),
    path("injuries", injuries_collection),
    path("injuries/<int:injury_id>", injury_update),
    path("positions", positions_list),
    path("meta/roster", roster_metadata),
    path("workflow/replacements/candidates", replacement_candidates),
    path("workflow/replacements/decisions", replacement_decisions_collection),
    path("workflow/replacements/decisions/<int:decision_id>", replacement_decision_update),
    path("admin/overview", admin_overview),
    path("admin/recommendations/recompute", admin_recompute_recommendations),
]