# Generated by Django 6.0.4 on 2026-04-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplacementDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notes", models.CharField(blank=True, max_length=280)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "injured_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_decisions_as_injured",
                        to="team_analytics.player",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_decisions",
                        to="team_analytics.position",
                    ),
                ),
                (
                    "replacement_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_decisions_as_replacement",
                        to="team_analytics.player",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="replacementdecision",
            index=models.Index(fields=["is_active", "created_at"], name="team_analyt_is_acti_883174_idx"),
        ),
        migrations.AddIndex(
            model_name="replacementdecision",
            index=models.Index(fields=["injured_player", "is_active"], name="team_analyt_injured_d9f0a8_idx"),
        ),
    ]
