# Generated by Django 6.0.4 on 2026-04-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_analytics', '0002_replacementdecision'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='replacementdecision',
            new_name='team_analyt_is_acti_dd9b7f_idx',
            old_name='team_analyt_is_acti_883174_idx',
        ),
        migrations.RenameIndex(
            model_name='replacementdecision',
            new_name='team_analyt_injured_b1962e_idx',
            old_name='team_analyt_injured_d9f0a8_idx',
        ),
    ]
